import random 
import json
from openpyxl import workbook as opyxl

def convert_txt_to_list(filename:str, encoding:str='utf-8')->list:
    """
    transform a txt file with medicine names into a list

    param filename: the name of the .txt file that needs to be converted
    param encoding: the encoding of the .txt file (default is 'utf-8')
    return: list with the medicines from the txt file
    """
    try:
        with open(filename, 'r', encoding=encoding) as f:
                return [line.strip() for line in f.readlines() if line.strip()]
    except FileNotFoundError:
        print(f"File {filename} not found.")
        return []
    except Exception as e:
        print(f"Error reading file {filename}: {e}")
        return []

def generate_interaction_matrix(medicines: list, min_value: int, max_value: int ) -> list:
    """
    create a matrix with random interaction values between medicines using numbers from 0 to 6

    param medicines: list with all medicines that will interact with each other
    param min_value: the minimum value for the range
    param max_value: the maximum value for the range
    return: matrix with all interaction values
    """

    matrix = [[0]*len(medicines) for _ in range(len(medicines))]

    for i in range(len(medicines)):
        for j in range(i+1, len(medicines)):
            value = random.randint(min_value, max_value)
            matrix[i][j] = value
            matrix[j][i] = value

    return matrix

def generate_excel(filename: str, medicines: list, matrix: list) -> None:
    """
    generate an Excel file representing the interactions created in "generate_interaction_matrix"

    param filename: the name of the resulting .xlsx file
    param medicines: same list of medicine names used in "generate_interaction_matrix"
    param matrix: matrix generated by the function "generate_interaction_matrix"
    return: nothing
    """
    wb = opyxl.Workbook()
    ws = wb.active
    ws.title = "Interações"
    for col, med in enumerate(medicines, start=2):
        ws.cell(row=1, column=col, value=med)
    for row, med in enumerate(medicines, start=2):
        ws.cell(row=row, column=1, value=med)
        for col in range(len(medicines)):
            ws.cell(row=row, column=col+2, value=matrix[row-2][col])
    wb.save(filename)
    return None

def create_prescriptions(medicines: list,min_value: int, max_value: int) -> dict:
    """
    randomly choose between 1 and 10 patients and create a prescription with 3 to 5 medicines for each one

    param medicines: list of medicines
    param min_value: the minimum value for the range
    param max_value: the maximum value for the range
    return: dictionary with generated prescriptions
    """
    people={ }
    
    for _ in range(random.randint(1,10)):
        prescription = []
        for _ in range(random.randint(3,5)):
            prescription.append(random.choice(medicines).strip())
        people[random.randint(min_value, max_value)] = prescription
    return people

def evaluate_danger(prescriptions: dict, matrix: list, medicines: list) -> list:
    """
    check the highest risk interaction between the medicines in each prescription

    param prescriptions: dictionary with generated prescriptions
    param matrix: matrix with the danger levels of medicine interactions
    param medicines: list of medicines
    return: list with the highest danger value for each prescription
    """
    max_list = []
    for key in prescriptions:
        danger = []
        max_danger= 0
        
        for i in range(len(prescriptions[key])):
            for j in range(i + 1,len(prescriptions[key])):                
                danger.append(matrix[medicines.index(prescriptions[key][i])][medicines.index(prescriptions[key][j])])
        for i in range(len(danger)):
            if max_danger < danger[i]:
                max_danger = danger[i]
        max_list.append(max_danger)

    
    return max_list

def count_dangerous_interactions(prescription: list, matrix: list) -> int:
    """
    count the number of interactions between the medicines in a prescription

    param prescription: list of prescribed medicines
    param matrix: matrix with the danger levels of medicine interactions
    return: value representing the number of interactions
    """
    count = 0
    for i in range(len(prescription)):
        for j in range(i + 1,len(prescription)):
            if matrix[i][j] != 0:
                count += 1
    return count

def save_json(data: dict, filename: str) -> None:
    """
    save the prescriptions in a .json file

    param data: the prescriptions that will be saved
    param filename: the name of the resulting .json file
    return: nothing
    """
    try:
        with open(filename, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=4)
    except Exception as e:
        print(f"Error saving JSON: {e}")
    return None

def encrypt_patient_numbers(prescriptions: dict, key: int) -> dict:
    """
    encrypt the patient numbers in the prescriptions using a Caesar cipher

    param prescriptions: the prescriptions that will be encrypted
    param key: value used in the Caesar cipher
    return: the prescriptions with encrypted patient numbers
    """
    for _ in range(len(prescriptions)):
        numero_utentes = []
        for i in prescriptions:            
            numero_utentes.append([int(d) for d in str(i)])
    ascii_listas = [[int(ord(str(digito))) + key % 256 for digito in sublista] for sublista in numero_utentes]
    no_ascii= [[chr(ascii_val) for ascii_val in sublista] for sublista in ascii_listas]
    lista_encriptada = [''.join(sublista) for sublista in no_ascii]
    encripted_dict = {lista_encriptada[i] : prescriptions[key] for i, key in enumerate(prescriptions)} 
    return encripted_dict
   
def decrypt_patient_numbers(prescriptions: dict, key: int) -> dict:
    """
    decrypt the patient numbers in the prescriptions using a Caesar cipher

    param prescriptions: the prescriptions that will be decrypted
    param key: value used in the Caesar cipher
    return: the prescriptions with decrypted patient numbers
    """
    for _ in range(len(prescriptions)):
        numero_utentes = []
        for i in prescriptions:
            numero_utentes.append(list(str(i)))
    ascii_listas = [[int(ord(str(digito))) - key % 256 for digito in sublista] for sublista in numero_utentes]
    no_ascii= [[chr(ascii_val) for ascii_val in sublista] for sublista in ascii_listas]
    lista_descriptada = [''.join(sublista) for sublista in no_ascii]
    descripted_dict = {lista_descriptada[i] : prescriptions[key] for i, key in enumerate(prescriptions)}
    return descripted_dict 

def folding_hash(prescriptions: dict, table_size: int, hash_key: int) -> list:
    """
    apply the folding hashing method to the patient numbers in the prescriptions

    param prescriptions: the prescriptions that will be hashed
    param table_size: the size of the hash table
    param hash_key: additional value used in the hash function
    return: list with the hashed patient numbers
    """
    hashed = []
    for key in prescriptions:
        key_str = str(key)
        fold_sum = sum(int(ord(digit)) for digit in key_str) + hash_key
        hashed_key = fold_sum % table_size
        hashed.append(hashed_key)
    return hashed

medicines = convert_txt_to_list("projeto_remedios/medicines.txt")
matriz = generate_interaction_matrix(medicines, 0, 6)
generate_excel("projeto_remedios/interacoes.xlsx", medicines, matriz)
prescription = create_prescriptions(medicines,100000000,999999999)
print(evaluate_danger(prescription,matriz,medicines))
encripted_prescription = encrypt_patient_numbers(prescription, 3)
print(encripted_prescription)
save_json(encripted_prescription, "projeto_remedios/prescription.json")
print(decrypt_patient_numbers(encripted_prescription, 3))
print([hex(hexadecimal) for hexadecimal in folding_hash((prescription), 256, 123987)])